type Dapp {
    id: ID!
    title: String
    author: String!
    address: String!
    network_id: String!
    blockchain_id: String!
    blockchain_name: String!
}

# The "Query" type is the root of all GraphQL queries.
# (A "Mutation" type will be covered later on.)
type Query {
  dapp(id: ID!): Dapp
  dapps: [Dapp]
}

type Mutation {
  saveDapp(title: String!): Dapp
}

schema {
  query: Query
  mutation: Mutation
}

